workflows:
  android-release:
    name: Android APK Release
    environment:
      flutter: stable
    scripts:
      - flutter pub get
      - flutter build apk --release --target-platform android-arm64
    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk
